# Generated by Django 5.1.3 on 2024-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='posts/'),
        ),
    ]
