name: Deploy Django API to Server

on:
  workflow_dispatch:  # Manual trigger through GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install sshpass
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Set up SSH and configure SSH connection
    - name: Set up SSH
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no "$SSH_USER@$SERVER_IP" "echo Connected"

    # Deploy to the server
    - name: Deploy to the server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        VENV_NAME: ${{ secrets.VENV_NAME }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SERVER_IP" << 'EOF'
          cd $PROJECT_PATH
          git pull origin master
          source $PROJECT_PATH/$VENV_NAME/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart apache2
          exit
        EOF