name: Deploy Django API to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Create deployment script
      run: |
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        set -e

        cd "$1"

        if [ ! -d ".git" ]; then
          echo "Initializing repository..."
          exit 1
        fi

        git pull origin master

        if [ ! -d "$2" ]; then
          python3 -m venv "$2"
        fi

        source "$2/bin/activate"

        pip install -r requirements.txt

        python manage.py migrate
        python manage.py collectstatic --noinput

        sudo systemctl restart apache2
        EOF
        chmod +x deploy.sh

    - name: Deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        VENV_NAME: ${{ secrets.VENV_NAME }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no deploy.sh "$SSH_USER@$SERVER_IP:/tmp/deploy.sh"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SERVER_IP" "bash /tmp/deploy.sh '$PROJECT_PATH' '$PROJECT_PATH/$VENV_NAME' && rm /tmp/deploy.sh"